# Generated by Django 2.2.5 on 2019-10-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_id',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='user_id',
        ),
    ]
