# Generated by Django 2.2.5 on 2019-10-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0003_auto_20191012_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='ride_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='ride',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rideshare_app.Ride'),
        ),
    ]
