# Generated by Django 2.2.5 on 2019-10-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rideshare_app', '0002_auto_20191012_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='ride',
            new_name='ride_id',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='ride',
            new_name='ride_id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='ride_id',
            field=models.ForeignKey(db_column='ride_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rideshare_app.Ride'),
        ),
    ]
